//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhamaPOS_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public item()
        {
            this.stocks = new HashSet<stock>();
        }
    
        public int itemId { get; set; }
        public int itemCode { get; set; }
        public string itemDescription { get; set; }
        public string itemCallingName { get; set; }
        public int itemUnitId { get; set; }
        public bool itemStatus { get; set; }
        public System.DateTime entryDate { get; set; }
        public string entryBy { get; set; }
    
        public virtual unit unit { get; set; }
        public virtual ICollection<stock> stocks { get; set; }
    }
}
