//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhamaPOS_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public long saleId { get; set; }
        public long saleBatchId { get; set; }
        public long itemStockId { get; set; }
        public long soldQuantity { get; set; }
        public decimal unitPrice { get; set; }
        public decimal amount { get; set; }
    
        public virtual saleBatch saleBatch { get; set; }
        public virtual stock stock { get; set; }
    }
}
