//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhamaPOS_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock
    {
        public stock()
        {
            this.sales = new HashSet<sale>();
        }
    
        public long stockId { get; set; }
        public int itemId { get; set; }
        public Nullable<decimal> itemUnitPriceBuying { get; set; }
        public decimal itemUnitPriceSelling { get; set; }
        public long StockQuantity { get; set; }
        public long runningQuantity { get; set; }
        public System.DateTime stockReceivedDate { get; set; }
        public Nullable<System.DateTime> stockClearedDate { get; set; }
        public bool isAvailable { get; set; }
        public Nullable<System.DateTime> stockMfdDate { get; set; }
        public System.DateTime stockExpDate { get; set; }
        public System.DateTime entryDate { get; set; }
        public string entryBy { get; set; }
    
        public virtual item item { get; set; }
        public virtual ICollection<sale> sales { get; set; }
    }
}
